name: Docker Testing

on:
  push:
    branches: testbranch
    paths:
      - 'docker/**'
      - 'docker-compose.yml'

jobs:
  docker-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Compose Build
        run: docker-compose build