name: Docker Testing

on:
  push:
    branches: testbranch
    paths:
      - '20220529yamamoto/docker/**'
      - '20220529yamamoto/docker-compose.yml'

jobs:
  docker-testing:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 20220529yamamoto

    steps:
      - uses: actions/checkout@v2

      - name: Docker Compose Build
        run: docker-compose build